"""dataset_explore.ipynb

Automatically generated by Colaboratory.
"""

!pip install --upgrade openai --quiet

import os
import openai
import pandas as pd
import logging
from io import StringIO

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s [INFO] %(message)s')

openai.api_key = os.environ.get("OPENAI_API_KEY")

# Connecting to Google Drive:
from google.colab import drive
drive.mount('/content/drive')

# -------------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------------
DATA_SOURCE_DIR = "/content/drive/My Drive/contracts"      
OUTPUT_DIR = "/content/drive/My Drive/labelled_datasets"      
FINAL_DATASET_DIR = "/content/drive/My Drive/final_datasets"    
MODEL_NAME = "gpt-4"

# Contract smell definitions sets
# Three variants of prompts:
smell_descriptions_textual = """
LongMethod: Overly Long Clauses. Clauses in contracts that are exceptionally long and contain many complex sentences. These clauses can be difficult to understand and may lead to misinterpretation. This is similar to how lengthy methods in code become hard to manage.
DataClumps: Repetitive Clauses. Clauses that are very similar or identical to each other, appearing multiple times within the contract. This indicates potential redundancy and makes the contract unnecessarily long, like repeated groups of variables in code.
TempField: Inconsistent Terms. Variations in the use of key terms or definitions throughout the contract. Inconsistent terminology can create confusion and ambiguity, akin to the use of temporary fields in code that complicates understanding.
DuplicateCode: Redundant Language. Phrases, sentences, or entire clauses that are repeated unnecessarily. This lengthens the contract without adding value and can make future updates more difficult. This often results from multiple drafters or copy-pasting, mirroring code duplication.
ExcessLegalese: Overuse of obscure legal terms and complex jargon. This makes the contract difficult to understand for non-specialists and may impede clarity even for legal professionals, similar to overusing comments to explain complex code segments.
"""

smell_descriptions_coding = """
These definitions are taken from the world of software code issues, but they can be mapped to match similar issues with legal contract.
LongMethod: Methods in code that are excessively long, containing too much logic. These methods are difficult to read, understand, and maintain, often leading to increased complexity and errors.
DataClumps: Groups of variables that are frequently used together, indicating poor abstraction and redundancy in the code. These clumps often point to missing encapsulation or poor design.
TempField: Fields that are only used intermittently in code, adding unnecessary clutter and complexity to the class. They make the code harder to understand and maintain.
DuplicateCode: Repeated code fragments across different parts of the system, increasing maintenance effort and introducing redundancy. Such duplication often occurs due to poor reuse or excessive copy-pasting.
ExcessLegalese: Overuse of comments in code to explain complex logic, making it harder to discern the true intent and structure of the code.
"""

smell_descriptions_extended = """
LongMethod: Overly Long Clauses. Clauses in contracts that are exceptionally long and contain many complex sentences. These clauses can be difficult to understand and may lead to misinterpretation.  Similar to how lengthy methods in software code become hard to manage.
DataClumps: Repetitive Clauses. Clauses that are very similar or identical to each other, appearing multiple times within the contract. This indicates potential redundancy and makes the contract unnecessarily long. like repeated groups of variables in code.
TempField: Inconsistent Terms. Variations in the use of key terms or definitions throughout the contract. Inconsistent terminology can create confusion and ambiguity. akin to the use of temporary fields in software code that complicates understanding.
DuplicateCode: Redundant Language. Phrases, sentences, or entire clauses that are repeated unnecessarily. This lengthens the contract without adding value and can make future updates more difficult. resulting from multiple drafters or copy-pasting, mirrors software code duplication.
ExcessLegalese: Overuse of obscure legal terms and complex jargon. This makes the contract difficult to understand for non-specialists and may impede clarity even for legal professionals. similar to overusing comments to explain complex softwaer code segments.
LazyClass: Software code that lacks specificity or detail, or is ambiguous, or clause that add no real legal weight as it is not detailed enough to be enforceable or effective, will only make the contract longer, more complex to understand.
InappropIntimacy: In software code, classes coupled too tightly run risks. Contracts often include dependecies between clauses or sentences that are tightly dependt within a clause.
"""

# -------------------------------------------------------------------------
# Functions
# -------------------------------------------------------------------------

def load_contracts_from_directory(data_dir: str) -> pd.DataFrame:
    """
    Loads contract texts and filenames from a specified directory.

    Args:
        data_dir (str): The directory path within Google Drive containing contract .txt files.

    Returns:
        pd.DataFrame: A dataframe with columns ['ContractName', 'ContractText'].
    """
    contracts_data = []
    for filename in os.listdir(data_dir):
        if filename.endswith(".txt"):
            file_path = os.path.join(data_dir, filename)
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                contract_text = f.read()
                contracts_data.append((filename, contract_text))
    return pd.DataFrame(contracts_data, columns=["ContractName", "ContractText"])


def identify_smells(contract_text: str, contract_name: str, smell_descriptions: str, model: str = MODEL_NAME) -> pd.DataFrame:
    """
    Identifies contract smells in a contract text using the OpenAI ChatCompletion API.

    Args:
        contract_text (str): The text of the contract.
        contract_name (str): The filename or identifier of the contract.
        smell_descriptions (str): The definitions or descriptions of the contract smells.
        model (str): The OpenAI model name to use.

    Returns:
        pd.DataFrame: A DataFrame with columns:
                      [ContractName, ClauseText, LongMethod, DataClumps, TempField, DuplicateCode, ExcessLegalese].
    """
    prompt = f"""
    Contract Name: {contract_name}

    Please parse the provided contract text into individual clauses.
    Then, for each clause, use the previously provided definitions to classify if any of the following contract smells are present: 
    LongMethod, DataClumps, TempField, DuplicateCode, ExcessLegalese. 
    Use '1' to indicate yes and '0' to indicate no.

    Return the result formatted as a table with columns:
    ContractName | ClauseText | LongMethod | DataClumps | TempField | DuplicateCode | ExcessLegalese

    Contract Text:
    {contract_text}
    """

    # Construct messages for chat completion
    messages = [
        {"role": "system", "content": f"You are a highly skilled lawyer analyzing contract issues, known as contract smells. Here are the definitions to guide you. {smell_descriptions}"},
        {"role": "user", "content": prompt}
    ]

    try:
        completion = openai.ChatCompletion.create(
            model=model,
            messages=messages,
            max_tokens=5000,
            temperature=0.7
        )
    except Exception as e:
        logging.error(f"Error occurred while classifying {contract_name}: {e}")
        return pd.DataFrame()

    identified_clauses = completion.choices[0].message.content.strip()

    # Attempt to parse the returned table into a DataFrame
    try:
        # First lines are header and separator.
        df = pd.read_csv(StringIO(identified_clauses), sep='\\s*\\|\\s*', engine='python', skiprows=[1], skipinitialspace=True)
        df = df.dropna(axis=1, how='all')
        return df
    except Exception as e:
        logging.warning(f"Could not parse output into a DataFrame for {contract_name}: {e}")
        return pd.DataFrame()

def clean_labeled_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Cleans and validates the labeled data DataFrame.
    Args:
        df (pd.DataFrame): The DataFrame for cleaning.

    Returns:
        pd.DataFrame: Cleaned and validated DataFrame.
    """
    # Expected columns
    expected_columns = ['ContractName', 'ClauseText', 'LongMethod', 'DataClumps', 'TempField', 'DuplicateCode', 'ExcessLegalese']
    for col in expected_columns:
        if col not in df.columns:
            logging.warning(f"Missing expected column '{col}'. Dropping this DF.")
            return pd.DataFrame()

    # Drop rows with null in critical columns
    df = df.dropna(subset=['ContractName', 'ClauseText'])

    # Validate resonable ClauseText length
    df = df[df['ClauseText'].str.len().between(50, 100000)]

    # Validate values in label columns
    label_cols = ['LongMethod', 'DataClumps', 'TempField', 'DuplicateCode', 'ExcessLegalese']
    for col in label_cols:
        # Coerce to string, strip, and ensure only '0' or '1'
        df[col] = df[col].astype(str).str.strip()
        df = df[df[col].isin(['0', '1'])]
    df[label_cols] = df[label_cols].astype(int)
    return df

def create_auto_labeled_dataset(contracts_df: pd.DataFrame, smell_descriptions: str, dataset_label: str) -> pd.DataFrame:
    """
    Given a dataframe of contracts & smell definitions, auto labels and builds the dataset.

    Args:
        contracts_df (pd.DataFrame): DataFrame with columns [ContractName, ContractText].
        smell_descriptions (str): Descriptions of the smells to be used in the prompt.
        dataset_label (str): A label indicating which dataset variant this is (e.g. 'Textual', 'Coding', 'Extended').

    Returns:
        pd.DataFrame: A concatenated DataFrame of all contracts' clauses and their labels.
    """
    all_results = pd.DataFrame()
    logging.info(f"Starting auto-labeling for dataset: {dataset_label}")

    for i, row in contracts_df.iterrows():
        contract_name = row['ContractName']
        contract_text = row['ContractText']

        df = identify_smells(contract_text, contract_name, smell_descriptions, model=MODEL_NAME)
        if not df.empty:
            df = clean_labeled_data(df)
            all_results = pd.concat([all_results, df], ignore_index=True)
        else:
            logging.warning(f"No valid results for contract: {contract_name}")

        # Periodically save partial results
        if (i + 1) % 25 == 0:
            partial_path = os.path.join(OUTPUT_DIR, f"{dataset_label}_auto_labeled_partial_{i+1}.csv")
            all_results.to_csv(partial_path, index=False)
            logging.info(f"Saved partial results to {partial_path}")

    # Final
    final_path = os.path.join(OUTPUT_DIR, f"{dataset_label}_auto_labeled_dataset.csv")
    all_results.to_csv(final_path, index=False)
    logging.info(f"Completed auto-labeling for dataset: {dataset_label}. Results saved to {final_path}")

    return all_results

# -------------------------------------------------------------------------
# Main Execution Flow (Example)
# -------------------------------------------------------------------------

# Load the contracts
contracts_df = load_contracts_from_directory(DATA_SOURCE_DIR)

# Create the three datasets as described:
textual_dataset = create_auto_labeled_dataset(contracts_df, smell_descriptions_textual, "Textual_Oriented")
coding_dataset = create_auto_labeled_dataset(contracts_df, smell_descriptions_coding, "Coding_Oriented")
extended_dataset = create_auto_labeled_dataset(contracts_df, smell_descriptions_extended, "Extended_Oriented")

logging.info("All steps completed.")
