# -*- coding: utf-8 -*-
"""CUADLegalBERT_MultiClass_Detection_ClassImbalance_HPFT.ipynb

Automatically generated by Colab.

"""

!pip install transformers
!pip install datasets
!pip install accelerate -U
!pip install transformers[torch] -U
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import Trainer, TrainingArguments

from huggingface_hub import notebook_login

notebook_login()
!pip install --quiet transformers datasets accelerate torch
!pip install optuna

import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from datasets import load_dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, precision_recall_fscore_support
from transformers import EarlyStoppingCallback
# ---------------------------------------
# Configuration
# ---------------------------------------
LABEL_COLUMNS = ['LongMethod', 'DataClumps', 'TempField', 'DuplicateCode', 'ExcessLegalese', 'LazyClass', 'InappropIntimacy']
BATCH_SIZE = 16
EPOCHS = 3
LEARNING_RATE = 1e-4
MAX_LENGTH = 128
MODEL_NAME = "alex-apostolo/legal-bert-base-cuad"
OUTPUT_DIR = "./models"
LOGS_DIR = "./logs"

# ---------------------------------------
# Load and Preprocess Datasets
# ---------------------------------------
autol_dataset = load_dataset('moriyad/autol_contract_smells')
hl_dataset = load_dataset('moriyad/hl_contract_smells')

def is_str(example):
    return isinstance(example['ClauseText'], str)

def keep_valid_rows(example):
    try:
        for col in LABEL_COLUMNS:
            if example.get(col) is None:
                return False
            val = int(float(example[col]))
            if val not in [0, 1]:
                return False
        return True
    except:
        return False

autol_dataset = autol_dataset.filter(is_str)
autol_dataset = autol_dataset.filter(keep_valid_rows)

hl_dataset = hl_dataset.filter(is_str)
hl_dataset = hl_dataset.filter(keep_valid_rows)

# Combinining datasets to include human label in training
train_df_autol = pd.DataFrame(autol_dataset['train'])
train_df_hl = pd.DataFrame(hl_dataset['train'])
combined_train_df = pd.concat([train_df_autol, train_df_hl], ignore_index=True)

# Create validation/test splits from combined data (80% train, 10% val, 10% test)
val_size = 0.1
test_size = 0.1
train_end = int(len(combined_train_df)*(1 - val_size - test_size))
val_end = int(len(combined_train_df)*(1 - test_size))

train_df = combined_train_df.iloc[:train_end].reset_index(drop=True)
val_df = combined_train_df.iloc[train_end:val_end].reset_index(drop=True)
test_df = combined_train_df.iloc[val_end:].reset_index(drop=True)

def convert_labels_multi(example):
    labels = [int(float(example[col])) for col in LABEL_COLUMNS]
    example['labels'] = labels
    return example

train_ds = Dataset.from_pandas(train_df)
val_ds = Dataset.from_pandas(val_df)
test_ds = Dataset.from_pandas(test_df)

# Apply label conversion
train_ds = train_ds.map(convert_labels_multi)
val_ds = val_ds.map(convert_labels_multi)
test_ds = test_ds.map(convert_labels_multi)

# Combine into a DatasetDict
final_dataset = DatasetDict({
    'train': train_ds,
    'validation': val_ds,
    'test': test_ds
})

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_function(examples):
    return tokenizer(examples['ClauseText'], truncation=True, padding='max_length', max_length=MAX_LENGTH)

# Tokenize datasets
train_ds = train_ds.map(tokenize_function, batched=True)
val_ds = val_ds.map(tokenize_function, batched=True)
test_ds = test_ds.map(tokenize_function, batched=True)

# Verify label shapes
example = train_ds[0]
assert isinstance(example['labels'], list) and len(example['labels']) == len(LABEL_COLUMNS), \
    "Labels are not in the expected [num_labels] format per example."

train_ds = train_ds.map(lambda x: {"labels": [float(i) for i in x["labels"]]})
val_ds = val_ds.map(lambda x: {"labels": [float(i) for i in x["labels"]]})
test_ds = test_ds.map(lambda x: {"labels": [float(i) for i in x["labels"]]})

# Convert to torch format
train_ds.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
val_ds.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
test_ds.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# Verify shape after formatting
batch = next(iter(torch.utils.data.DataLoader(train_ds, batch_size=32)))
print("Input IDs shape:", batch['input_ids'].shape)  
print("Labels shape:", batch['labels'].shape)        

# Class Imbalance Handling
train_labels = np.array([ex['labels'].numpy() for ex in train_ds])
pos_counts = train_labels.sum(axis=0)
neg_counts = len(train_ds) - pos_counts
class_weights = (neg_counts / pos_counts).astype(float)
class_weights = torch.tensor(class_weights, dtype=torch.float)

# -----------------------------------------------------------------------------
# Custom Model & Metrics To Support Class Specific Weights & MultiLabel Training
# -----------------------------------------------------------------------------

class MultilabelModel(nn.Module):
    def __init__(self, model_name, num_labels, class_weights):
        super(MultilabelModel, self).__init__()
        self.model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)
        self.class_weights = class_weights

    def forward(self, input_ids=None, attention_mask=None, labels=None):
        outputs = self.model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        if labels is not None:
            labels = labels.float()
            loss_fct = nn.BCEWithLogitsLoss(weight=self.class_weights.to(logits.device))
            loss = loss_fct(logits, labels)
            return {'loss': loss, 'logits': logits}
        return {'logits': logits}

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = (logits > 0).astype(int)
    # Macro metrics
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro', zero_division=0)
    acc = accuracy_score(labels, preds)
    per_class_f1 = precision_recall_fscore_support(labels, preds, average=None, zero_division=0)[2]
    try:
        probs = 1 / (1 + np.exp(-logits))
        auc_score = roc_auc_score(labels, probs, average='macro')
    except ValueError:
        auc_score = float('nan')
    metrics = {
        'accuracy': acc,
        'macro_f1': f1,
        'macro_precision': precision,
        'macro_recall': recall,
        'macro_auc': auc_score
    }
    # Add per-class F1 metrics
    for i, cls in enumerate(LABEL_COLUMNS):
        metrics[f'f1_{cls}'] = per_class_f1[i]
    return metrics

def model_init():
    return MultilabelModel(MODEL_NAME, num_labels=len(LABEL_COLUMNS), class_weights=class_weights)


training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model='macro_f1',
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir=LOGS_DIR,
    logging_steps=100,
    fp16=torch.cuda.is_available()
)

trainer = Trainer(
    model_init=model_init,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

# --------------------------------------------
# Hyper Parameters Fine Tuning - Trail Setup 
# --------------------------------------------

def hp_space(trial):
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 5e-4, log=True),
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [8,16,32]),
        "num_train_epochs": trial.suggest_int("num_train_epochs", 2, 5)
    }

best_run = trainer.hyperparameter_search(
    direction="maximize",
    hp_space=hp_space,
    n_trials=5,
    backend="optuna"
)

print("Best hyperparameters found:", best_run.hyperparameters)

# Update trainer with best hyperparameters
for n, v in best_run.hyperparameters.items():
    setattr(trainer.args, n, v)

# Re-run training with best parameters
trainer.train()
print("Final Evaluation on Test Set:")
results = trainer.evaluate(test_ds)
print(results)