# -*- coding: utf-8 -*-
"""CUADLegalBERT_SingleClass_Detection_ClassImbalance_HPFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10S4u5AJLDXAg27z3r6_wGYSyon0GP3y3

# CUAD Trained LegalBERT for contract smells detection

*   Single Class Fine Tuning
*   Class Imbalanca Handling
*   Hyperparams Fine Tuning

"""

!pip install transformers
!pip install datasets
!pip install accelerate -U
!pip install transformers[torch] -U
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import Trainer, TrainingArguments

from huggingface_hub import notebook_login

notebook_login()
!pip install --quiet transformers datasets accelerate torch

import numpy as np

import matplotlib.pyplot as plt
from datasets import load_dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, precision_recall_fscore_support
from transformers import EarlyStoppingCallback
# ---------------------------------------
# Configuration
# ---------------------------------------
LABEL_COLUMNS = ['LongMethod', 'DataClumps', 'TempField', 'DuplicateCode', 'ExcessLegalese']
BATCH_SIZE = 16
EPOCHS = 3
LEARNING_RATE = 1e-4
MAX_LENGTH = 128
MODEL_NAME = "alex-apostolo/legal-bert-base-cuad"
OUTPUT_DIR = "./models"
LOGS_DIR = "./logs"

# ---------------------------------------
# Load and Preprocess Datasets
# ---------------------------------------
autol_dataset = load_dataset('moriyad/autol_contract_smells')

def is_str(example):
    return isinstance(example['ClauseText'], str)

def keep_valid_rows(example):
    try:
        for col in LABEL_COLUMNS:
            if example.get(col) is None:
                return False
            val = int(float(example[col]))
            if val not in [0, 1]:
                return False
        return True
    except:
        return False

autol_dataset = autol_dataset.filter(is_str)
autol_dataset = autol_dataset.filter(keep_valid_rows)

train_df_autol = pd.DataFrame(autol_dataset['train'])

# Create validation/test splits from combined data (80% train, 10% val, 10% test)
val_size = 0.1
test_size = 0.1

allDatasetsDicts = {}
for class_column in LABEL_COLUMNS:
  data = {'ClauseText': train_df_autol['ClauseText'], 'labels': train_df_autol[class_column]}
  df = pd.DataFrame(data)
  df.reset_index(inplace=True)
  df.rename(columns={'index': 'idx'}, inplace=True)
  train_end = int(len(df) * (1 - val_size - test_size))
  val_end = int(len(df) * (1 - test_size))

  train_df = df.iloc[:train_end].reset_index(drop=True)
  val_df = df.iloc[train_end:val_end].reset_index(drop=True)
  test_df = df.iloc[val_end:].reset_index(drop=True)

  # Now convert each split to a Dataset
  train_ds = Dataset.from_pandas(train_df)
  val_ds = Dataset.from_pandas(val_df)
  test_ds = Dataset.from_pandas(test_df)

  allDatasetsDicts[class_column] = DatasetDict({
      'train': train_ds,
      'validation': val_ds,
      'test': test_ds
  })
  print(allDatasetsDicts[class_column])



import torch
import torch.nn as nn

!pip install optuna
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score
from transformers import AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments
from datasets import load_dataset, Dataset, DatasetDict
import optuna

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_function(examples):
    return tokenizer(examples['ClauseText'], truncation=True, padding='max_length', max_length=MAX_LENGTH)

class SingleLabelModel(nn.Module):
    def __init__(self, model_name, class_weight):
        super(SingleLabelModel, self).__init__()
        self.model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=1)
        self.class_weight = class_weight

    def forward(self, input_ids=None, attention_mask=None, labels=None):
        outputs = self.model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits.squeeze(-1)  # shape: [batch_size]
        if labels is not None:
            labels = labels.float()
            loss_fct = nn.BCEWithLogitsLoss(weight=self.class_weight.to(logits.device))
            loss = loss_fct(logits, labels)
            return {'loss': loss, 'logits': logits}
        return {'logits': logits}

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    # logits: [batch_size], labels: [batch_size]
    preds = (logits > 0).astype(int)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary', zero_division=0)
    acc = accuracy_score(labels, preds)

    try:
        probs = 1 / (1 + np.exp(-logits))
        auc_score = roc_auc_score(labels, probs)
    except ValueError:
        auc_score = float('nan')

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall,
        'auc': auc_score
    }

example = train_ds[0]
print(example)

allClassesTrainers = {}
allClassesResults = {}

for class_column in LABEL_COLUMNS:
  allClassesResults[class_column] = {'test_ds': None, 'results': None, 'best_params': None}

  train_ds = allDatasetsDicts[class_column]['train'].map(tokenize_function, batched=True)
  val_ds = allDatasetsDicts[class_column]['validation'].map(tokenize_function, batched=True)
  test_ds = allDatasetsDicts[class_column]['test'].map(tokenize_function, batched=True)

  # Check single label format
  example = train_ds[0]
  print(example)
  #assert LABEL_COLUMN in example, f"Dataset does not have the label column: {LABEL_COLUMN}"

  # Convert labels to float
  train_ds = train_ds.map(lambda x: {"labels": float(x['labels'])})
  val_ds = val_ds.map(lambda x: {"labels": float(x['labels'])})
  test_ds = test_ds.map(lambda x: {"labels": float(x['labels'])})

  # Set format to torch
  train_ds.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
  val_ds.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
  test_ds.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

  # Verify shapes
  batch = next(iter(torch.utils.data.DataLoader(train_ds, batch_size=32)))
  print("Input IDs shape:", batch['input_ids'].shape)   # [32, MAX_LENGTH]
  print("Labels shape:", batch['labels'].shape)         # [32]

  # Class Imbalance Handling
  # Extract all labels into a numpy array
  all_labels = np.array([float(ex['labels'].item()) for ex in train_ds])  # Convert tensor to float
  pos_count = all_labels.sum()
  neg_count = len(train_ds) - pos_count
  class_weight = torch.tensor((neg_count / pos_count), dtype=torch.float) if pos_count > 0 else torch.tensor(1.0)

  def model_init():
      return SingleLabelModel(MODEL_NAME, class_weight=class_weight)

  training_args = TrainingArguments(
      output_dir=OUTPUT_DIR,
      eval_strategy="epoch",
      save_strategy="epoch",
      load_best_model_at_end=True,
      metric_for_best_model='f1',
      num_train_epochs=EPOCHS,
      per_device_train_batch_size=BATCH_SIZE,
      per_device_eval_batch_size=BATCH_SIZE,
      logging_dir=LOGS_DIR,
      logging_steps=100,
      fp16=torch.cuda.is_available(),
      remove_unused_columns=False
  )

  allClassesTrainers[class_column] = Trainer(
      model_init=model_init,
      args=training_args,
      train_dataset=train_ds,
      eval_dataset=val_ds,
      compute_metrics=compute_metrics
  )

  allClassesResults[class_column]['test_ds'] = test_ds

def hp_space(trial):
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 5e-4, log=True),
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [8,16,32]),
        "num_train_epochs": trial.suggest_int("num_train_epochs", 2, 5)
    }

for class_column in LABEL_COLUMNS:

  best_run = allClassesTrainers[class_column].hyperparameter_search(
      direction="maximize",
      hp_space=hp_space,
      n_trials=5,
      backend="optuna"
  )

  print("Best hyperparameters found:", best_run.hyperparameters)
  allClassesResults[class_column]['best_params'] = best_run.hyperparameters
  # Update trainer with best hyperparameters
  for n, v in best_run.hyperparameters.items():
      setattr(allClassesTrainers[class_column].args, n, v)

  # Re-run training with best parameters
  allClassesTrainers[class_column].train()

  # Evaluate on test set
  print("Final Evaluation on Test Set:")
  results = allClassesTrainers[class_column].evaluate(allClassesResults[class_column]['test_ds'])
  allClassesResults[class_column]['results'] = results
  print(results)

for class_column in LABEL_COLUMNS:
  print("Final Evaluation on Class:", class_column)
  print(allClassesResults[class_column]['results'])