# -*- coding: utf-8 -*-
"""CUADLegalBERT_contract_smells_detection_hl_autol.ipynb

Automatically generated by Colab.

# Installing required packages
"""

!pip install transformers
!pip install datasets
!pip install accelerate -U
!pip install transformers[torch] -U

from huggingface_hub import notebook_login
notebook_login()

import torch
import pandas as pd
import numpy as np
from datasets import Dataset, DatasetDict, load_dataset
from transformers import AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# ---------------------------------------
# Configuration Variables
# ---------------------------------------
MODEL_NAME = "alex-apostolo/legal-bert-base-cuad"
OUTPUT_DIR = "./models"
LOGS_DIR = "./logs"
BATCH_SIZE = 160
NUMBER_OF_EPOCHS = 3
LEARNING_RATE = 1e-4
GRADIENT_ACCUMULATION_STEPS = 4
USE_FP16 = True
MAX_LENGTH = 128

LABEL_COLUMNS = ['LongMethod', 'DataClumps', 'TempField', 'DuplicateCode', 'ExcessLegalese', 'LazyClass', 'InappropIntimacy']
HL_LABEL_COLUMNS = ['LazyClass', 'InappropIntimacy']

# ---------------------------------------
# Loading and Filtering Datasets
# ---------------------------------------
autol_dataset = load_dataset('moriyad/autol_contract_smells')
hl_dataset = load_dataset('moriyad/hl_contract_smells')

def is_str(example):
    return isinstance(example['ClauseText'], str)

def filter_valid_rows(dataset, columns):
    def is_valid(example):
        try:
            for col in columns:
                if example[col] is None:
                    return False
                value = int(float(example[col]))
                if value not in [0, 1]:
                    return False
            return True
        except ValueError:
            return False

    return dataset.filter(is_str).filter(is_valid)

autol_dataset = filter_valid_rows(autol_dataset, LABEL_COLUMNS)
hl_dataset = filter_valid_rows(hl_dataset, HL_LABEL_COLUMNS)

# ---------------------------------------
# Preparing Individual Label Datasets
# ---------------------------------------
def create_label_datasets(dataset, columns):
    datasets = {}
    for column in columns:
        data = {
            'ClauseText': dataset['train']['ClauseText'],
            'labels': dataset['train'][column]
        }
        df = pd.DataFrame(data)
        df.reset_index(inplace=True)
        df.rename(columns={'index': 'idx'}, inplace=True)
        new_dataset = Dataset.from_pandas(df)

        # Splitting the dataset
        split = new_dataset.train_test_split(test_size=0.2)
        datasets[column] = DatasetDict({
            'train': split['train'],
            'test': split['test']
        })
    return datasets

hl_datasets = create_label_datasets(hl_dataset, HL_LABEL_COLUMNS)
autol_datasets = create_label_datasets(autol_dataset, LABEL_COLUMNS)

# ---------------------------------------
# Tokenization
# ---------------------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_function(examples):
    return tokenizer(examples['ClauseText'], truncation=True, padding='max_length', max_length=MAX_LENGTH)

def tokenize_datasets(datasets):
    for label, dataset_dict in datasets.items():
        for split in ['train', 'test']:
            datasets[label][split] = dataset_dict[split].map(tokenize_function, batched=True)
            datasets[label][split].set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

    return datasets

hl_datasets = tokenize_datasets(hl_datasets)
autol_datasets = tokenize_datasets(autol_datasets)

# ---------------------------------------
# Compute Metrics
# ---------------------------------------
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# ---------------------------------------
# Training Arguments
# ---------------------------------------
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    learning_rate=LEARNING_RATE,
    num_train_epochs=NUMBER_OF_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    logging_dir=LOGS_DIR,
    logging_steps=100,
    do_train=True,
    do_eval=True,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=USE_FP16,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    metric_for_best_model='f1'
)

# ---------------------------------------
# Trainer Initialization and Training
# ---------------------------------------
def train_and_evaluate(datasets, model_name):
    results = {}
    trainers = {}
    for label, dataset_dict in datasets.items():
        print(f"Training model for {label}...")
        model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=1)
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=dataset_dict['train'],
            eval_dataset=dataset_dict['test'],
            compute_metrics=compute_metrics
        )
        trainer.train()
        results[label] = trainer.evaluate(dataset_dict['test'])
        trainers[label] = trainer
    return results, trainers

hl_results, hl_trainers = train_and_evaluate(hl_datasets, MODEL_NAME)
autol_results, autol_trainers = train_and_evaluate(autol_datasets, MODEL_NAME)

# ---------------------------------------
# Cross-Evaluation
# ---------------------------------------
# Evaluate auto-labeled trainers on human-labeled datasets
autol_eval_on_hl = {}
for class_dataset in hl_datasets:
    autol_eval_on_hl[class_dataset] = autol_trainers[class_dataset].evaluate(hl_datasets[class_dataset]['test'])

print("Evaluating auto-labeled trainers on human-labeled datasets:")
print(autol_eval_on_hl)

# Evaluate human-labeled trainers on auto-labeled datasets
hl_eval_on_autol = {}
for class_dataset in hl_datasets:
    hl_eval_on_autol[class_dataset] = hl_trainers[class_dataset].evaluate(autol_datasets[class_dataset]['test'])

print("Evaluating human-labeled trainers on auto-labeled datasets:")
print(hl_eval_on_autol)
