# -*- coding: utf-8 -*-
"""hf_prompt_adjust.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11E3hAIeknHxzyX00LdiNvzLzRSj-wmkM
"""

import os
import pandas as pd
import json
from openai import OpenAI

# ---------------------------------------
# Configuration Variables
# ---------------------------------------
DRIVE_PATH_LAZY = "/content/drive/My Drive/MyModels/legal-bert-base-coding/autol_incorrect_predictions_lazyclass.csv"
DRIVE_PATH_INAPROP = "/content/drive/My Drive/MyModels/legal-bert-base-coding/autol_incorrect_predictions_InappropIntimacy.csv"
OUTPUT_PATH_LAZY = "/content/drive/My Drive/MyModels/legal-bert-base-coding/autol_fewshot_predictions_lazyclass.csv"
OUTPUT_PATH_INAPROP = "/content/drive/My Drive/MyModels/legal-bert-base-coding/autol_fewshot_predictions_InappropIntimacy.csv"
OPENAI_API_KEY = ""

# Expanded contract smells definitions
SMELL_DESCRIPTIONS = """
LazyClass: Code that lacks specificity or detail, or is ambiguous, or clause that adds no real legal weight as it is not detailed enough to be enforceable or effective, will only make the contract longer, more complex to understand.
InappropIntimacy: In code, classes coupled too tightly run risks. Contracts often include dependencies between clauses or sentences that are tightly dependent within a clause.
"""

# ---------------------------------------
# Load Clause Data
# ---------------------------------------
print("Loading clause data...")
preds_lazy = pd.read_csv(DRIVE_PATH_LAZY)
preds_inaprop = pd.read_csv(DRIVE_PATH_INAPROP)

print("LazyClass Data Sample:")
print(preds_lazy.head())

print("InappropIntimacy Data Sample:")
print(preds_inaprop.head())

# ------------------------------------------------------
# Select Few-Shot Examples Based on Max Probability Diff
# ------------------------------------------------------
def select_few_shots(df, column):
    max_value = df[column].max()
    min_value = df[column].min()
    median_value = df[column].median()

    max_row = df[df[column] == max_value].head(1)
    min_row = df[df[column] == min_value].head(1)
    median_row = df.iloc[(df[column] - median_value).abs().argsort()[:1]]

    return pd.concat([max_row, min_row, median_row])

inaprop_few_shots = select_few_shots(preds_inaprop, 'Prob_Diff')
lazy_few_shots = select_few_shots(preds_lazy, 'Prob_Diff')

# Combine examples into formatted strings
lazy_shots = '\n'.join([f"{i + 1}: {row['ClauseText']}" for i, row in lazy_few_shots.iterrows()])
inaprop_shots = '\n'.join([f"{i + 1}: {row['ClauseText']}" for i, row in inaprop_few_shots.iterrows()])

SMELL_EXAMPLES = f"LazyClass:\n{lazy_shots}\n\nInappropIntimacy:\n{inaprop_shots}"  

print("Few-shot examples prepared.")

# ---------------------------------------
# Few-Shot Classification
# ---------------------------------------
def identify_clause_smells_few_shots(clause_text, smell_descriptions, smell_examples):
    """
    Classifies contract smells for a given clause text using OpenAI's API.

    Returns:
        dict: Classification results for the clause.
    """
    client = OpenAI(api_key=OPENAI_API_KEY)

    prompt = f"""
    Please classify based on the contract smells definitions provided below, and examples provided if any of the following contract issues are present in the provided clause text: LazyClass, InappropIntimacy. Use '1' to indicate presence and '0' to indicate absence of each smell.

    Return only a single JSON object with the properties: ClauseText, LazyClass, InappropIntimacy.

    Definitions:
    {smell_descriptions}

    Examples:
    {smell_examples}

    Clause Text:
    {clause_text}
    """

    messages = [
        {"role": "system", "content": f"You are a highly skilled lawyer analyzing contract issues based on this list: {smell_descriptions} and these examples {smell_examples}"},
        {"role": "user", "content": prompt}
    ]

    try:
        completion = client.chat.completions.create(
            model="gpt-4",
            max_tokens=4096,
            n=1,
            temperature=0.7,
            messages=messages
        )
        return json.loads(completion.choices[0].message.content)
    except Exception as e:
        print(f"Error occurred: {e}")
        return {}

# ---------------------------------------
# Apply Few-Shot Classification
# ---------------------------------------
def apply_smell_classification(df, label):
    def classify_row(row):
        smells = identify_clause_smells_few_shots(row['ClauseText'], SMELL_DESCRIPTIONS, SMELL_EXAMPLES)
        return smells.get(label, 0)

    df[f'autol_few_{label}'] = df.apply(lambda row: classify_row(row), axis=1)
    return df

print("Classifying LazyClass clauses...")
preds_lazy = apply_smell_classification(preds_lazy, 'LazyClass')

print("Classifying InappropIntimacy clauses...")
preds_inaprop = apply_smell_classification(preds_inaprop, 'InappropIntimacy')

# ---------------------------------------
# Save Results
# ---------------------------------------
print("Saving results...")
preds_lazy.to_csv(OUTPUT_PATH_LAZY, index=False)
preds_inaprop.to_csv(OUTPUT_PATH_INAPROP, index=False)

# -----------------------------------------------------------
# Evaluate Impact of Few-Shot Classification - 40% Corrected
# -----------------------------------------------------------
def evaluate_impact(df, label):
    count_fixed = df[(df['Predicted_Class'] != df['True_Class']) & (df[f'autol_few_{label}'] == df['True_Class'])].shape[0]
    print(f"Rows where Predicted_Class != True_Class but autol_few_{label} == True_Class: {count_fixed}")

print("Evaluating impact for LazyClass...")
evaluate_impact(preds_lazy, 'LazyClass')

print("Evaluating impact for InappropIntimacy...")
evaluate_impact(preds_inaprop, 'InappropIntimacy')
