"""pca_explore.ipynb

Automatically generated by Colaboratory.
"""
!pip install --upgrade pip
!pip install --upgrade transformers datasets accelerate torch
!pip install datasets
!pip install accelerate -U
!pip install transformers[torch] -U

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from transformers import AutoTokenizer, AutoModel, Trainer, TrainingArguments
import torch
import pandas as pd
from datasets import Dataset, DatasetDict, load_dataset


from huggingface_hub import notebook_login
notebook_login()

# -------------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------------
CLASS_COLUMNS = ['LongMethod', 'DataClumps', 'TempField', 'DuplicateCode', 'ExcessLegalese']
CLASS_HL_COLUMNS = ['LazyClass', 'InappropIntimacy']
CLASS_EXTEND_COLUMNS = ['LongMethod', 'DataClumps', 'TempField', 'DuplicateCode', 'ExcessLegalese', 'LazyClass', 'InappropIntimacy']

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# -------------------------------------------------------------------------
# Helper Functions
# -------------------------------------------------------------------------

def is_str(example):
    """
    Checks if 'ClauseText' in the example is a string.
    """
    return isinstance(example['ClauseText'], str)

def keep_valid_rows(example, labels):
    """
    Validates that each class column is either '0' or '1' (after converting from string/float if needed).
    Returns True if valid, False otherwise.
    """
    try:
        for column in labels:
            if example[column] is None:
                return False
            value_as_int = int(float(example[column]))
            if value_as_int not in [0, 1]:
                return False
        return True
    except (ValueError, TypeError):
        # If conversion fails or data is malformed, discard the row
        return False

def convert_labels(example, labels):
    """
    Converts class label columns from string/float to integers.
    """
    for category in labels:
        example[category] = int(float(example[category]))
    return example


# -------------------------------------------------------------------------
# PCA Functions
# -------------------------------------------------------------------------

def get_embeddings(texts, tokenizer, model, batch_size=32):
    """
    Obtain embeddings for a list of texts using a transformer model.
    We'll use the [CLS] token embeddings as a basic representation.
    """
    model.eval()
    embeddings = []
    with torch.no_grad():
        for i in range(0, len(texts), batch_size):
            batch_texts = texts[i:i+batch_size]
            inputs = tokenizer(batch_texts, return_tensors='pt', padding=True, truncation=True, max_length=128)
            outputs = model(**inputs)
            # CLS token embedding is at index 0
            cls_embeddings = outputs.last_hidden_state[:, 0, :]
            embeddings.append(cls_embeddings.cpu())
    return torch.cat(embeddings, dim=0).numpy()

def run_pca_plot(
    df: pd.DataFrame,
    tokenizer,
    model,
    label_col: str = 'DuplicateCode',
    sample_size: int = 500,
    random_state: int = 42,
    title: str = 'PCA of Clause Embeddings'
):
    """
    Runs PCA on a subset of the given DataFrame (df), projects embeddings to 2D, and plots them colored by the specified label_col.

    Args:
        df (pd.DataFrame): DataFrame containing a 'ClauseText' column and a binary label column.
        tokenizer: A tokenizer compatible with the chosen model.
        model: A transformer model used to generate embeddings.
        label_col (str): The column in df to use for coloring points. Must be binary (0/1).
        sample_size (int): Number of clauses to sample for PCA visualization.
        random_state (int): Random seed for sampling reproducibility.
        title (str): Title for the plot.
    """
    # Sample the DataFrame
    sample_size = min(sample_size, len(df))
    sample_df = df.sample(sample_size, random_state=random_state)
    sample_texts = sample_df['ClauseText'].tolist()

    # Obtain embeddings for the sampled clauses
    clause_embeddings = get_embeddings(sample_texts, tokenizer, model)  # Assuming get_embeddings is defined

    # Apply PCA to reduce dimensionality
    pca = PCA(n_components=2)
    reduced_embeddings = pca.fit_transform(clause_embeddings)

    # Extract labels for visualization
    labels = sample_df[label_col].values
    plt.figure(figsize=(10, 8))
    plt.scatter(reduced_embeddings[labels==0, 0], reduced_embeddings[labels==0, 1], alpha=0.7, label=f'{label_col}=0')
    plt.scatter(reduced_embeddings[labels==1, 0], reduced_embeddings[labels==1, 1], alpha=0.7, label=f'{label_col}=1')

    plt.title(title)
    plt.xlabel('PC1')
    plt.ylabel('PC2')
    plt.legend()
    plt.show()


    # -------------------------------------------------------------------------
# Main Data Loading and Processing
# -------------------------------------------------------------------------

# Load datasets from Hugging Face
coding_oriented_dataset = load_dataset('moriyad/descriptive_contract_smells')
textual_oriented_dataset = load_dataset('moriyad/descriptive_textual_contract_smells')
autolbl_dataset = load_dataset('moriyad/autol_contract_smells')
hl_dataset = load_dataset('moriyad/hl_contract_smells')


# Filter out rows where ClauseText is not a string
coding_dataset = coding_oriented_dataset.filter(is_str)
textual_dataset = textual_oriented_dataset.filter(is_str)
autol_dataset = autolbl_dataset.filter(is_str)
hl_dataset = hl_dataset.filter(is_str)

# Filter out invalid rows (ensure all class columns are 0 or 1)
coding_dataset = coding_dataset.filter(lambda ex: keep_valid_rows(ex, CLASS_COLUMNS))
textual_dataset = textual_dataset.filter(lambda ex: keep_valid_rows(ex, CLASS_COLUMNS))
autol_dataset = autol_dataset.filter(lambda ex: keep_valid_rows(ex, CLASS_EXTEND_COLUMNS))
hl_dataset = hl_dataset.filter(lambda ex: keep_valid_rows(ex, CLASS_HL_COLUMNS))

# Convert labels to integers (0 or 1)
coding_dataset = coding_dataset['train'].map(lambda ex: convert_labels(ex, CLASS_COLUMNS))
textual_dataset = textual_dataset['train'].map(lambda ex: convert_labels(ex, CLASS_COLUMNS))
autol_dataset = autol_dataset['train'].map(lambda ex: convert_labels(ex, CLASS_EXTEND_COLUMNS))
hl_dataset = hl_dataset['train'].map(lambda ex: convert_labels(ex, CLASS_HL_COLUMNS))

# Convert datasets to DataFrames for exploration
coding_df = pd.DataFrame(coding_dataset)
textual_df = pd.DataFrame(textual_dataset)
autol_df = pd.DataFrame(autol_dataset)
hl_df = pd.DataFrame(hl_dataset)

run_pca_plot(coding_df, tokenizer, model, label_col='DuplicateCode', title='Coding Oriented (DuplicateCode)')
run_pca_plot(textual_df, tokenizer, model, label_col='DuplicateCode', title='Textual Oriented (DuplicateCode)')
run_pca_plot(autol_df, tokenizer, model, label_col='InappropIntimacy', title='Extended-labeled (InappropIntimacy)')
run_pca_plot(hl_df, tokenizer, model, label_col='InappropIntimacy', title='Human-labeled (InappropIntimacy)')